Section "Device"
    Identifier  "fbdev"
    Driver      "fbdev"
    Option      "Rotate" "CW"
    Option      "fbdev" "/dev/fb0"
EndSection

Section "Screen"
    Identifier  "Default Screen"
    Device      "fbdev"
    DefaultDepth 24
EndSection

Section "ServerFlags"
    Option "BlankTime" "0"
    Option "StandbyTime" "0"
    Option "SuspendTime" "0"
    Option "OffTime" "0"
EndSection
